
import React, { useState } from "react";
import Head from "next/head";
import styles from "@/ui/styles/Home.module.css";

import AppBar from "@/ui/components/AppBar";
import InputSearch from "@/ui/components/InputSearch";
import Grid from '@mui/material/Grid2';
import AppTable from "@/ui/components/AppTable";
import { Box } from "@mui/material";


export default function Home() {

  const [searchTerm, setSearchTerm] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />

      <main className={styles.main}>
        <Grid container spacing={2} alignItems={"center"}>
          <Grid size={{ xs: 12, sm: 12, md: 7, lg: 9 }}>
            <h2>Funcionários</h2>
          </Grid>
          <Grid alignItems={"end"} size={{xs: 12,  sm: 12, md: 5, lg: 3 }}>
            <InputSearch onSearch={setSearchTerm}/>
          </Grid>
        </Grid>
        <Box mt={4}>
          <AppTable searchTerm={searchTerm}/>
        </Box>
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
}
